/* Copyright (c) The m-m-m Team, Licensed under the Apache License, Version 2.0
 * http://www.apache.org/licenses/LICENSE-2.0 */
package io.github.mmm.db.name;

import java.util.Collection;
import java.util.List;

import io.github.mmm.base.io.UncheckedAppendable;
import io.github.mmm.base.lang.ToString;
import io.github.mmm.db.ddl.column.DbColumn;
import io.github.mmm.db.ddl.constraint.DbConstraint;
import io.github.mmm.db.ddl.index.DbIndex;
import io.github.mmm.db.ddl.table.DbTable;

/**
 * Database object with a {@link #getName() name}. A database object can represent one of the following things:
 * <ul>
 * <li>{@link DbTable} (including view, synonym, or materialzed view)</li>
 * <li>{@link DbColumn}</li>
 * <li>{@link DbConstraint}</li>
 * <li>{@link DbIndex}</li>
 * </ul>
 * Please note that a {@link DbObject} can also be a create statement. In such case the represented object may not
 * physically exist in the database (yet).
 *
 * @since 1.0.0
 */
public interface DbObject extends ToString {

  /**
   * @return the name of this {@link DbObject}. Shall never be {@code null}.
   */
  default String getName() {

    return getName(DbNamingStrategy.of());
  }

  /**
   * @param namingStrategy the {@link DbNamingStrategy} to use. May be {@code null} to get the raw name. For some kind
   *        of database objects (e.g. {@link DbConstraint} or {@link DbIndex}) the raw name may even be {@code null} and
   *        will then be auto-generated by the naming strategy.
   * @return the {@link #getName() name} formatted or even auto-generated using the given {@link DbNamingStrategy}. If
   *         the given {@link DbNamingStrategy} is {@code null}, this method return the raw name that can even be
   *         {@code null} in cases described above.
   */
  String getName(DbNamingStrategy namingStrategy);

  /**
   * @return {@code true} if the name is derived from the Java world (e.g. {@link Class#getSimpleName() simple class
   *         name}), {@code false} otherwise (already specific for database).
   * @see io.github.mmm.bean.BeanType#getStableName()
   * @see io.github.mmm.bean.BeanType#getSimpleName()
   */
  default boolean hasJavaName() {

    return false;
  }

  /**
   * @param values the {@link Collection} with the values to append.
   * @param appendable the {@link UncheckedAppendable}.
   * @param mode the mode of the string format.
   * @see #toString(UncheckedAppendable, int)
   */
  static void append(Collection<?> values, UncheckedAppendable appendable, int mode) {

    if (values == null) {
      values = List.of();
    }
    appendable.append('(');
    boolean first = true;
    for (Object value : values) {
      if (value instanceof ToString ts) {
        ts.toString(appendable, mode);
      } else {
        appendable.append(value);
      }
      if (first) {
        first = false;
      } else {
        appendable.append(',');
      }
    }
    appendable.append(')');
  }

}
